### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by npcole** [simialbi/quill-smart-break#3]
I'm getting an import error when I try to install and use this module.  Is there any chance you could provide a fuller install guide?

**Comment by simialbi** [comment]
Could you post some code? How did you try to use it? What error did you get?

**Comment by npcole** [comment]
So I've:

- downloaded the source.
- run the following to build:
      > npm install
      > bundle install --path vendor/bundle
      > npm run build:webpack

In my html I have:

<script src="quill-smart-break-master/dist/smart-breaker.js"></script>

But when I run:

Quill.register('modules/smart-breaker', SmartBreaker);

I get an error that SmartBreaker is not defined. 

I realize I'm probably doing this all wrong ;-)

**Comment by simialbi** [comment]
Could you post full code of html file you import the script and initialize quill? 
Did you first load quill, then smart breaker, then initalize?
